name: customkamera
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/jsons/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter_black.ttf
        - asset: assets/fonts/inter_bold.ttf
        - asset: assets/fonts/inter_extra_bold.ttf
        - asset: assets/fonts/inter_extra_light.ttf
        - asset: assets/fonts/inter_light.ttf
        - asset: assets/fonts/inter_medium.ttf
        - asset: assets/fonts/inter_regular.ttf
        - asset: assets/fonts/inter_semi_bold.ttf
        - asset: assets/fonts/inter_thin.ttf